image: node:12

before_script:
  - bash scripts/ci-install.sh

#cache:
#  paths:
#    - node_modules/

test:lint:
  script:
    - bash scripts/lint.sh

# LTS
test:node:12:
  script:
    - bash scripts/build.sh

test:node:11:
  image: node:11
  script:
    - bash scripts/build.sh

# LTS
test:node:10:
  image: node:10
  script:
    - bash scripts/build.sh

# LTS
test:node:8:
  image: node:8
  script:
    - bash scripts/build.sh

publish:artifacts:
  stage: deploy
#  only:
#    - tags
#    - triggers
  script:
    - bash scripts/build.sh
  artifacts:
    paths:
      - packages/_lib-dist/dist/
