image: node:12

before_script:
  - bash scripts/ci-install.sh

#cache:
#  paths:
#    - node_modules/

test:lint:
  script:
    - bash scripts/lint.sh

# LTS
test:node:16:
  image: node:16
  script:
    - bash scripts/build.sh

test:node:15:
  image: node:15
  script:
    - bash scripts/build.sh

# LTS
test:node:14:
  image: node:14
  script:
    - bash scripts/build.sh

# LTS
test:node:12:
  script:
    - bash scripts/build.sh

publish:artifacts:
  stage: deploy
#  only:
#    - tags
#    - triggers
  script:
    - bash scripts/build.sh
  artifacts:
    paths:
      - packages/_lib-dist/dist/
