image: node:11

before_script:
  - bash scripts/ci-install.sh

#cache:
#  paths:
#    - node_modules/

test:lint:
  script:
    - bash scripts/lint.sh

test:node:11:
  script:
    - bash scripts/build.sh

# LTS
test:node:10:
  image: node:10.13.0
  script:
    - bash scripts/build.sh

# LTS
test:node:8:
  image: node:8
  script:
    - bash scripts/build.sh
